query scoreboardQuery($competitionId: ID!, $params: CompetitionAthleteListParams) {
  competition(competitionId: $competitionId) {
    competitionAthleteList(params: $params) {
      competitionAthletes {
        id
        firstName
        lastName
        lot
        bodyWeight
        total
        calcTotal
        squatTotal
        benchPressTotal
        deadliftTotal
        club {
          name
        }
        ageCategory {
          name
        }
        bodyWeightCategory {
          id
          name
        }
        competitionAthleteAttempts {
          weight
          status
          discipline
          attempt
        }
      }
    }
  }
}
